// Code generated by `aru view:build` from header.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package docs

import (
	kyse__fmt "fmt"
	kyse__template "html/template"
	kyse__io "io"

	kyse__view "github.com/arandu-io/hesape/view"
	"github.com/arandu-io/kyse/icons"
	swagger "github.com/hyz-is/arandu-swagger"
)

//line resources/views/docs/header.kyse.go:10

type HeaderViewData = swagger.SwaggerViewData

//line storage/framework/views/docs/header.go:22

func init() { kyse__view.Register("docs.header", renderDocsHeader) }

// renderDocsHeader renders docs.header.
func renderDocsHeader(kyse__w kyse__io.Writer, kyse__data any) error {
	kyse__d, kyse__ok := kyse__data.(HeaderViewData)
	if !kyse__ok {
		return kyse__view.WrongData("docs.header", "HeaderViewData", kyse__data)
	}
	_ = kyse__d
	d := kyse__d
	_ = d
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<div class=\"business-context\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<div class=\"flex items-center gap-2 text-sm text-muted-foreground\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<a href=\"")
	}
	if kyse__err == nil {
		var kyse__v1 string
//line resources/views/docs/header.kyse.go:16
		kyse__v1, kyse__err = kyse__view.TextURL(kyse__d.HomeURLOrDefault())
//line storage/framework/views/docs/header.go:52
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "resources/views/docs/header.kyse.go:16", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v1)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\" class=\"hover:text-foreground transition-colors flex items-center gap-1.5\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t")
	}
	if kyse__err == nil {
//line resources/views/docs/header.kyse.go:17
		var kyse__v2 kyse__template.HTML = icons.House(icons.Props{})
//line storage/framework/views/docs/header.go:68
		_, kyse__err = kyse__io.WriteString(kyse__w, string(kyse__v2))
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<span>Workspace</span>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t</a>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<span>/</span>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<span class=\"text-foreground font-medium flex items-center gap-1.5\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t")
	}
	if kyse__err == nil {
//line resources/views/docs/header.kyse.go:22
		var kyse__v3 kyse__template.HTML = icons.BookOpen(icons.Props{})
//line storage/framework/views/docs/header.go:92
		_, kyse__err = kyse__io.WriteString(kyse__w, string(kyse__v3))
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<span>Documentação da API</span>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t</span>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<div class=\"flex items-center gap-2\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<span class=\"badge border border-border bg-muted/60 text-muted-foreground text-xs px-2.5 py-0.5 rounded-md font-mono\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\tOAS 3.1\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t</span>\n")
	}
//line resources/views/docs/header.kyse.go:30
	if kyse__d.Version != "" {
//line storage/framework/views/docs/header.go:121
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<span class=\"badge border border-primary/30 bg-primary/10 text-primary text-xs px-2.5 py-0.5 rounded-md font-medium\">\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tv")
		}
		if kyse__err == nil {
//line resources/views/docs/header.kyse.go:32
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Version)))
//line storage/framework/views/docs/header.go:131
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t</span>\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<header class=\"business-heading\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<p class=\"onboarding-eyebrow\">INTEGRAÇÃO E DESENVOLVEDOR</p>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<h1>")
	}
	if kyse__err == nil {
//line resources/views/docs/header.kyse.go:41
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Title)))
//line storage/framework/views/docs/header.go:164
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</h1>\n")
	}
//line resources/views/docs/header.kyse.go:42
	if kyse__d.Description != "" {
//line storage/framework/views/docs/header.go:171
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<p class=\"max-w-3xl text-sm text-muted-foreground mt-1\">")
		}
		if kyse__err == nil {
//line resources/views/docs/header.kyse.go:43
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Description)))
//line storage/framework/views/docs/header.go:178
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</p>\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<div class=\"flex items-center gap-2.5\">\n")
	}
//line resources/views/docs/header.kyse.go:47
	if kyse__d.BackURLOrDefault() != "" {
//line storage/framework/views/docs/header.go:192
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<a class=\"btn\" href=\"")
		}
		if kyse__err == nil {
			var kyse__v4 string
//line resources/views/docs/header.kyse.go:48
			kyse__v4, kyse__err = kyse__view.TextURL(kyse__d.BackURLOrDefault())
//line storage/framework/views/docs/header.go:200
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "resources/views/docs/header.kyse.go:48", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v4)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\" data-variant=\"secondary\">\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t")
		}
		if kyse__err == nil {
//line resources/views/docs/header.kyse.go:49
			var kyse__v5 kyse__template.HTML = icons.ArrowLeft(icons.Props{})
//line storage/framework/views/docs/header.go:216
			_, kyse__err = kyse__io.WriteString(kyse__w, string(kyse__v5))
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t<span>")
		}
		if kyse__err == nil {
//line resources/views/docs/header.kyse.go:50
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.BackTextOrDefault())))
//line storage/framework/views/docs/header.go:228
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</span>\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t</a>\n")
		}
	}
//line resources/views/docs/header.kyse.go:53
	if kyse__d.SpecPath != "" {
//line storage/framework/views/docs/header.go:239
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<a class=\"btn\" href=\"")
		}
		if kyse__err == nil {
			var kyse__v6 string
//line resources/views/docs/header.kyse.go:54
			kyse__v6, kyse__err = kyse__view.TextURL(kyse__d.SpecPath)
//line storage/framework/views/docs/header.go:247
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "resources/views/docs/header.kyse.go:54", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v6)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\" target=\"_blank\" rel=\"noopener noreferrer\">\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t")
		}
		if kyse__err == nil {
//line resources/views/docs/header.kyse.go:55
			var kyse__v7 kyse__template.HTML = icons.Code(icons.Props{})
//line storage/framework/views/docs/header.go:263
			_, kyse__err = kyse__io.WriteString(kyse__w, string(kyse__v7))
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t<span>OpenAPI JSON</span>\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t")
		}
		if kyse__err == nil {
//line resources/views/docs/header.kyse.go:57
			var kyse__v8 kyse__template.HTML = icons.ArrowUpRight(icons.Props{})
//line storage/framework/views/docs/header.go:278
			_, kyse__err = kyse__io.WriteString(kyse__w, string(kyse__v8))
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t</a>\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<button type=\"button\" class=\"btn\" data-arandu-swagger-authorize>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t")
	}
	if kyse__err == nil {
//line resources/views/docs/header.kyse.go:61
		var kyse__v9 kyse__template.HTML = icons.Lock(icons.Props{})
//line storage/framework/views/docs/header.go:297
		_, kyse__err = kyse__io.WriteString(kyse__w, string(kyse__v9))
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<span>Autorizar</span>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t</button>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</header>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	return kyse__err
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
)
