// Code generated by `aru view:build` from swagger.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package docs

import (
	kyse__fmt "fmt"
	kyse__template "html/template"
	kyse__io "io"

	kyse__view "github.com/arandu-io/hesape/view"
	swagger "github.com/hyz-is/arandu-swagger"
)

//line resources/views/docs/swagger.kyse.go:9

type SwaggerViewData = swagger.SwaggerViewData

//line storage/framework/views/docs/swagger.go:21

func init() { kyse__view.Register("docs.swagger", renderDocsSwagger) }

// renderDocsSwagger renders docs.swagger.
func renderDocsSwagger(kyse__w kyse__io.Writer, kyse__data any) error {
	kyse__d, kyse__ok := kyse__data.(SwaggerViewData)
	if !kyse__ok {
		return kyse__view.WrongData("docs.swagger", "SwaggerViewData", kyse__data)
	}
	_ = kyse__d
	d := kyse__d
	_ = d
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<!doctype html>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<html lang=\"")
	}
	if kyse__err == nil {
//line resources/views/docs/swagger.kyse.go:31
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Locale))
//line storage/framework/views/docs/swagger.go:50
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\" class=\"dark\" data-theme=\"dark\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<head>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<meta charset=\"utf-8\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<title>")
	}
	if kyse__err == nil {
//line resources/views/docs/swagger.kyse.go:35
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Title)))
//line storage/framework/views/docs/swagger.go:70
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</title>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<link rel=\"icon\" href=\"")
	}
	if kyse__err == nil {
		var kyse__v1 string
//line resources/views/docs/swagger.kyse.go:36
		kyse__v1, kyse__err = kyse__view.TextURL(kyse__d.FaviconOrDefault())
//line storage/framework/views/docs/swagger.go:82
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "resources/views/docs/swagger.kyse.go:36", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v1)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</head>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<body class=\"dark-theme\">\n")
	}
	if kyse__err == nil {
		kyse__err = kyse__view.Include(kyse__w, "docs.topbar", kyse__data)
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		kyse__err = kyse__view.Include(kyse__w, "docs.container", kyse__data)
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</body>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</html>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	return kyse__err
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
)
