// Code generated by `aru view:build` from container.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package docs

import (
	kyse__fmt "fmt"
	kyse__template "html/template"
	kyse__io "io"

	kyse__view "github.com/arandu-io/hesape/view"
	swagger "github.com/hyz-is/arandu-swagger"
)

//line resources/views/docs/container.kyse.go:9

type ContainerViewData = swagger.SwaggerViewData

//line storage/framework/views/docs/container.go:21

func init() { kyse__view.Register("docs.container", renderDocsContainer) }

// renderDocsContainer renders docs.container.
func renderDocsContainer(kyse__w kyse__io.Writer, kyse__data any) error {
	kyse__d, kyse__ok := kyse__data.(ContainerViewData)
	if !kyse__ok {
		return kyse__view.WrongData("docs.container", "ContainerViewData", kyse__data)
	}
	_ = kyse__d
	d := kyse__d
	_ = d
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<div id=\"swagger-ui\" class=\"arandu-swagger-container\" hx-boost=\"false\"></div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<link rel=\"stylesheet\" href=\"")
	}
	if kyse__err == nil {
		var kyse__v1 string
//line resources/views/docs/container.kyse.go:15
		kyse__v1, kyse__err = kyse__view.TextURL(kyse__d.UIPath)
//line storage/framework/views/docs/container.go:51
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "resources/views/docs/container.kyse.go:15", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v1)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "/assets/5.32.14/swagger-ui.css\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<link rel=\"stylesheet\" href=\"")
	}
	if kyse__err == nil {
		var kyse__v2 string
//line resources/views/docs/container.kyse.go:16
		kyse__v2, kyse__err = kyse__view.TextURL(kyse__d.UIPath)
//line storage/framework/views/docs/container.go:68
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "resources/views/docs/container.kyse.go:16", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v2)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "/theme.css\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<script src=\"")
	}
	if kyse__err == nil {
		var kyse__v3 string
//line resources/views/docs/container.kyse.go:17
		kyse__v3, kyse__err = kyse__view.TextURL(kyse__d.UIPath)
//line storage/framework/views/docs/container.go:85
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "resources/views/docs/container.kyse.go:17", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v3)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "/assets/5.32.14/swagger-ui-bundle.js\"></script>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<script src=\"")
	}
	if kyse__err == nil {
		var kyse__v4 string
//line resources/views/docs/container.kyse.go:18
		kyse__v4, kyse__err = kyse__view.TextURL(kyse__d.UIPath)
//line storage/framework/views/docs/container.go:102
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "resources/views/docs/container.kyse.go:18", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v4)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "/swagger-initializer.js\"></script>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	return kyse__err
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
)
