// Code generated by `aru view:build` from topbar.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package docs

import (
	kyse__fmt "fmt"
	kyse__template "html/template"
	kyse__io "io"

	kyse__view "github.com/arandu-io/hesape/view"
	"github.com/arandu-io/kyse/icons"
	swagger "github.com/hyz-is/arandu-swagger"
)

//line resources/views/docs/topbar.kyse.go:10

type TopbarViewData = swagger.SwaggerViewData

//line storage/framework/views/docs/topbar.go:22

func init() { kyse__view.Register("docs.topbar", renderDocsTopbar) }

// renderDocsTopbar renders docs.topbar.
func renderDocsTopbar(kyse__w kyse__io.Writer, kyse__data any) error {
	kyse__d, kyse__ok := kyse__data.(TopbarViewData)
	if !kyse__ok {
		return kyse__view.WrongData("docs.topbar", "TopbarViewData", kyse__data)
	}
	_ = kyse__d
	d := kyse__d
	_ = d
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<header class=\"arandu-swagger-topbar\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<div class=\"arandu-swagger-topbar-wrapper\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<div class=\"arandu-swagger-topbar-start\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<a\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\thref=\"")
	}
	if kyse__err == nil {
		var kyse__v1 string
//line resources/views/docs/topbar.kyse.go:18
		kyse__v1, kyse__err = kyse__view.TextURL(kyse__d.HomeURLOrDefault())
//line storage/framework/views/docs/topbar.go:58
		if kyse__err != nil {
			kyse__err = kyse__fmt.Errorf("%s: %w", "resources/views/docs/topbar.kyse.go:18", kyse__err)
		} else {
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v1)
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\tclass=\"arandu-swagger-logo-link\"\n")
	}
//line resources/views/docs/topbar.kyse.go:20
	if kyse__d.LogoTarget != "" {
//line storage/framework/views/docs/topbar.go:73
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\ttarget=\"")
		}
		if kyse__err == nil {
//line resources/views/docs/topbar.kyse.go:21
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.LogoTarget))
//line storage/framework/views/docs/topbar.go:80
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t>\n")
	}
//line resources/views/docs/topbar.kyse.go:24
	if kyse__d.LogoURLOrDefault() != "" {
//line storage/framework/views/docs/topbar.go:91
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t<img src=\"")
		}
		if kyse__err == nil {
			var kyse__v2 string
//line resources/views/docs/topbar.kyse.go:25
			kyse__v2, kyse__err = kyse__view.TextURL(kyse__d.LogoURLOrDefault())
//line storage/framework/views/docs/topbar.go:99
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "resources/views/docs/topbar.kyse.go:25", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v2)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\" alt=\"")
		}
		if kyse__err == nil {
//line resources/views/docs/topbar.kyse.go:25
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.BrandOrDefault()))
//line storage/framework/views/docs/topbar.go:112
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\" class=\"arandu-swagger-logo\">\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t<span class=\"arandu-swagger-title\">")
	}
	if kyse__err == nil {
//line resources/views/docs/topbar.kyse.go:27
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.BrandOrDefault())))
//line storage/framework/views/docs/topbar.go:124
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</span>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t</a>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<div class=\"arandu-swagger-topbar-end\">\n")
	}
//line resources/views/docs/topbar.kyse.go:31
	if kyse__d.BackURLOrDefault() != "" {
//line storage/framework/views/docs/topbar.go:140
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t<a\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\thref=\"")
		}
		if kyse__err == nil {
			var kyse__v3 string
//line resources/views/docs/topbar.kyse.go:33
			kyse__v3, kyse__err = kyse__view.TextURL(kyse__d.BackURLOrDefault())
//line storage/framework/views/docs/topbar.go:151
			if kyse__err != nil {
				kyse__err = kyse__fmt.Errorf("%s: %w", "resources/views/docs/topbar.kyse.go:33", kyse__err)
			} else {
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__v3)
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\tclass=\"arandu-swagger-back-link\"\n")
		}
//line resources/views/docs/topbar.kyse.go:35
		if kyse__d.BackTarget != "" {
//line storage/framework/views/docs/topbar.go:166
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t\ttarget=\"")
			}
			if kyse__err == nil {
//line resources/views/docs/topbar.kyse.go:36
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.BackTarget))
//line storage/framework/views/docs/topbar.go:173
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\"\n")
			}
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t>\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t")
		}
		if kyse__err == nil {
//line resources/views/docs/topbar.kyse.go:39
			var kyse__v4 kyse__template.HTML = icons.ArrowLeft(icons.Props{})
//line storage/framework/views/docs/topbar.go:188
			_, kyse__err = kyse__io.WriteString(kyse__w, string(kyse__v4))
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t<span>")
		}
		if kyse__err == nil {
//line resources/views/docs/topbar.kyse.go:40
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.BackTextOrDefault())))
//line storage/framework/views/docs/topbar.go:200
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</span>\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t</a>\n")
		}
	}
//line resources/views/docs/topbar.kyse.go:43
	if !kyse__d.DisableThemeToggle {
//line storage/framework/views/docs/topbar.go:211
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t<button type=\"button\" class=\"arandu-swagger-theme-toggle\" aria-label=\"")
		}
		if kyse__err == nil {
//line resources/views/docs/topbar.kyse.go:44
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Translate("Toggle theme")))
//line storage/framework/views/docs/topbar.go:218
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\" title=\"")
		}
		if kyse__err == nil {
//line resources/views/docs/topbar.kyse.go:44
			_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Translate("Toggle theme")))
//line storage/framework/views/docs/topbar.go:226
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\">\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t<span class=\"arandu-swagger-glyph-light\" aria-hidden=\"true\">")
		}
		if kyse__err == nil {
//line resources/views/docs/topbar.kyse.go:45
			var kyse__v5 kyse__template.HTML = icons.Sun(icons.Props{})
//line storage/framework/views/docs/topbar.go:237
			_, kyse__err = kyse__io.WriteString(kyse__w, string(kyse__v5))
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</span>\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t\t<span class=\"arandu-swagger-glyph-dark\" aria-hidden=\"true\">")
		}
		if kyse__err == nil {
//line resources/views/docs/topbar.kyse.go:46
			var kyse__v6 kyse__template.HTML = icons.Moon(icons.Props{})
//line storage/framework/views/docs/topbar.go:249
			_, kyse__err = kyse__io.WriteString(kyse__w, string(kyse__v6))
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "</span>\n")
		}
		if kyse__err == nil {
			_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t</button>\n")
		}
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</header>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	return kyse__err
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
)
